CREATE TABLE IF NOT EXISTS tax_invoices (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tax_invoice_no VARCHAR(50) NOT NULL,
    tax_invoice_type VARCHAR(30) NOT NULL,
    vat_type VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    voucher_id BIGINT NULL,
    issue_date DATE NOT NULL,
    supplier_business_no VARCHAR(20) NOT NULL,
    supplier_name VARCHAR(100) NOT NULL,
    supplier_representative_name VARCHAR(100) NULL,
    supplier_email VARCHAR(100) NULL,
    recipient_business_no VARCHAR(20) NOT NULL,
    recipient_name VARCHAR(100) NOT NULL,
    recipient_representative_name VARCHAR(100) NULL,
    recipient_email VARCHAR(100) NULL,
    supply_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    vat_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    total_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    external_approval_no VARCHAR(100) NULL,
    external_status VARCHAR(50) NULL,
    failure_reason VARCHAR(500) NULL,
    memo VARCHAR(500) NULL,
    issue_requested_at DATETIME NULL,
    issued_at DATETIME NULL,
    sent_at DATETIME NULL,
    cancelled_at DATETIME NULL,
    amended_at DATETIME NULL,
    created_by VARCHAR(100) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_tax_invoices_no (tax_invoice_no),
    KEY idx_tax_invoices_type_status (tax_invoice_type, status),
    KEY idx_tax_invoices_issue_date (issue_date),
    KEY idx_tax_invoices_voucher_id (voucher_id),
    KEY idx_tax_invoices_supplier_business_no (supplier_business_no),
    KEY idx_tax_invoices_recipient_business_no (recipient_business_no),
    CONSTRAINT chk_tax_invoices_amounts_non_negative CHECK (supply_amount >= 0 AND vat_amount >= 0 AND total_amount >= 0),
    CONSTRAINT chk_tax_invoices_total_matches CHECK (total_amount = supply_amount + vat_amount)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tax_invoice_lines (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tax_invoice_id BIGINT NOT NULL,
    line_no INT NOT NULL,
    item_name VARCHAR(150) NOT NULL,
    unit VARCHAR(30) NULL,
    quantity DECIMAL(15,2) NULL,
    unit_price DECIMAL(15,2) NULL,
    supply_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    vat_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    total_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    description VARCHAR(255) NULL,
    PRIMARY KEY (id),
    KEY idx_tax_invoice_lines_invoice_id (tax_invoice_id),
    CONSTRAINT fk_tax_invoice_lines_invoice
        FOREIGN KEY (tax_invoice_id) REFERENCES tax_invoices (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT chk_tax_invoice_lines_amounts_non_negative CHECK (supply_amount >= 0 AND vat_amount >= 0 AND total_amount >= 0),
    CONSTRAINT chk_tax_invoice_lines_total_matches CHECK (total_amount = supply_amount + vat_amount)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
